### ISSUE TITLE
Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by brossi** [king-prawns/w5kit-cli#1]
macOS High Sierra (ver. 10.13.6)
Node: 11.9.0
NPM: 6.7.0
Yarn: 1.13.0

## Observation
Attempting to run the `w4kit` command after installing the module results in a fatal exception:

```
HOST$ npm install -g w4kit-cli
/Users/brossi/.npm-packages/bin/w4kit -> /Users/brossi/.npm-packages/lib/node_modules/w4kit-cli/index.js
+ w4kit-cli@1.1.0
updated 1 package in 2.901s
HOST$ w4kit
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/brossi/.npm-packages/lib/node_modules/w4kit-cli/node_modules/nodegit/dist/nodegit.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```

## Resolution
1. After flailing around a bit, I uninstalled **w4kit-cli** and then reinstalled with no issues. 
1. Attempting to re-run the `w4kit` command still failed. 
1. After monkey patching **w4kit-cli**'s _package.json_ manifest to use `nodegit-v0.24.0` instead of the default `nodegit-v0.22.2`, I cleaned out and rebuilt the node_modules directory with `npm install`.
1. Re-run `w4kit`; success:

![w4kit-cli](https://user-images.githubusercontent.com/1556963/52481988-0d44d800-2b7e-11e9-8654-d0aa018c96ab.jpg)

**Comment by brossi** [comment]
I'm not exactly sure if this is something affecting all macOS installations or if it is a local ENV issue on my side, but in case it helps anyone else, here's a bug report and steps to fix. I've submitted a [pull request](https://github.com/king-prawns/w4kit-cli/pull/2) with the single line version correction, but I'm not knowledgeable enough to know if _nodegit-v0.22.2_ was specified for a particular reason, or if it was simply a dependency which had not been updated in a while.
